"""make conversations.grade_id nullable

Revision ID: b505433e3797
Revises: ba7ef64360f1
Create Date: 2026-10-07 21:13:34.673813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b505433e3797'
down_revision: Union[str, Sequence[str], None] = 'ba7ef64360f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
